name: Deploy Main Branch To S3 and Invalidate CloundFront Cache
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
    steps:
        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: ./
            bucket: ${{ secrets.S3_BUCKET_NAME }}
            bucket-region: ap-northeast-2
            dist-id: ${{ secrets.CF_ID }}
            invalidation: /
            delete-removed: true
            no-cache: true
            private: true
            filesToInclude: ".*/*,*/*,**"
        - name: pushover-actions
          uses: umahmood/pushover-actions@main
          env:
            PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}
            PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
          with:
            status: ${{ job.status }}
            title: '천일에너지 홈페이지 배포완료'
            message: '천일에너지 홈페이지 배포완료'
